spring:
  application:
    name: kyc-notifications
  profiles:
    active: dev
  jackson:
    default-property-inclusion: NON_NULL

management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
    external-services:
      enabled: true
  info:
    build:
      enabled: false

kyc-messages:
  catalog:
    messages:
      "000":
        code: KYC-NOTIFICATIONS-000
        message: Unexpected Error
        type: ERROR
      "001":
        code: KYC-NOTIFICATIONS-001
        message: The request is invalid
        type: ERROR
      "002":
        code: KYC-NOTIFICATIONS-002
        message: Cannot assign more notifications to this customer
        type: ERROR
      "003":
        code: KYC-NOTIFICATIONS-003
        message: The operation could not be performed
        type: ERROR