spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 45000
          max-interval: 80000
          multiplier: 1.3
          max-attempts: 3
  redis:
    host: 127.0.0.1
    port: 6379

eureka:
  client:
    enabled: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9100/eureka

kyc-config:
  number-notifications: 10

logging:
  level:
    root: INFO
    com.kyc: INFO
    org.springframework: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE